### ISSUE TITLE
Using Cerberus on a primitive platform

### ISSUE THREAD

**Issue by ghost** [TedGoas/Cerberus#268]
Hi Ted, i'm not sure if you monitor this channel but i thought i should ask, just in case.

i've found Cerberus in the desperate search for an HTML email template that will somehow play nicely with the idiotic platform i have to try and placate when structuring content for the IT support comms sent out by the company i do work for, as well as work within microsoft outlook.

This system is called 'service desk plus' and is managed by a group called manageengine. As i understand it, the dev our side has to cut paste the HTML email markup into a single field entry, which then strips out any <head> and <body> tags. Why? apparently these present a 'security risk'.

To cut a long and painful story short, i basically am trying to get this platform to ingest an HTML doc without a <head> or <body>tag, that will just about play nice with outlook. i've had a look through your Responsive template and it seems from what little i can understand to be pretty robust. My question (i think) is - as someone who still battles to comprehend the pitfalls around HTML email generation, is there any chance that your Responsive template could render correctly without these two tags? Effectively taking the contents between the <body> tags and injecting them into the rudimentary GUI? i would do this myself except am limited to petitioning the eldery developer who controls the system here to please trial any content i bring in for testing, which is challenging to say the least.

**Comment by TedGoas** [comment]
I absolutely monitor these Github issues :)

These templates should mostly work without the `<head>` section and everything in it. A few email clients like Gmail strip out the `<head>` tag, so most of the CSS is inlined to combat this.

Honestly I'm not sure what would happen if you remove the `<body>` tag. I hadn't previously heard this tag is a security risk and would love to hear more about how it is. You could trying using a service like [Putsmail](https://putsmail.com) to send yourself a test without these tags to see how it renders in Outlook.

**Comment by ghost** [comment]
This is fantastic Ted, thanks a ton for your feedback. 

I'd not heard of Putsmail either so will see if that can remove the extra live testing step. 

I'll give it a crack, and let you know if it's a success!


Thanks again!

**Comment by TedGoas** [comment]
@tetsuobodyhammer Howdy, any update on this?

**Comment by ghost** [comment]
> 
> 
> @tetsuobodyhammer Howdy, any update on this?


Hi Ted, unfortunately, yes - I'm wary of pasting the actual markup into GitHub as it stems from customer content, so i've forwarded this to you separately though to show what's happening there.

With any luck you can see the extent of the change from the basic comparison between the two sets of HTML. it's very odd. even the anchor elements are changed for some reason.

At this point, we've suggested to Ops that the system is now out of date and may not be fit for purpose any longer as any attempt to suggest that the platform owner consider our feedback is met with refusal.

**Comment by TedGoas** [comment]
Ahh sorry to hear. I see what you put into the system looks fairly clean, are we able to say your issue lies with the system and not these templates?

**Comment by ghost** [comment]
I think that's definitely the case, yes!On 11 Nov 2021 12:19, Ted Goas ***@***.***> wrote:
Ahh sorry to hear. I see what you put into the system looks fairly clean, are we able to say your issue lies with the system and not these templates?

**Comment by TedGoas** [comment]
Thanks, gonna close this for now since the issue isn't with the code in this repo.
