### ISSUE TITLE
Why duplicating styles for Button in hybrid template?

### ISSUE THREAD

**Issue by Binetri** [TedGoas/Cerberus#274]
Ted, thanks for your hard work. It is really very difficult to make up HTML for e-mail for different clients. I want to understand a little more than just copy and paste :) Explain, please, for what purpose to duplicate styles `border-radius: 4px; background: #222222;`  for `<td>` and for `<a>` tags on these lines?

https://github.com/TedGoas/Cerberus/blob/a2318a28a598cef4d86ef0a30c160431fe49b462/cerberus-hybrid.html#L285-L287

And duplicate classes for `:hover` events:

https://github.com/TedGoas/Cerberus/blob/a2318a28a598cef4d86ef0a30c160431fe49b462/cerberus-hybrid.html#L163-L168

**Comment by TedGoas** [comment]
One is for the actual link (`<a href>`) and one is for the `<table>` surrounding it. Some email clients don't allow us to apply box-model styles to an inline element like `<a>`, so we wrap it in a table to give it the appearance of a button even if the whole rectangle isn't clickable. Does that make sense?

**Comment by Binetri** [comment]
Thanks for the clarification, Ted.
It seems to me that if part of the button is not pressed, then it is confusing. I tested on a small number of available devices and did not find where duplicate styles for the tag `td` could be useful, since tag `a` already has a `padding: 13px 17px;`.

**Comment by TedGoas** [comment]
Which email clients did you test? Were some Windows Outlooks clients among them?

**Comment by Binetri** [comment]
I have tested: Thunderbird on PC; Gmail in Google Chrome on PC; Gmail app on Andriod; Mail.ru in Google Chrome on PC and Android; Mail.ru app on andriod. Unfortunately, none of my friends use Windows Outlook.
You can show a screenshot of the Windows Outlook what happens if you remove `class` and `style` attributes from `td` tag?

**Comment by TedGoas** [comment]
This is what happens in desktop Outlook and Office 365 on Windows when we remove the styles from the parent `<td>`:

<img width="190" alt="Screen Shot 2021-11-20 at 12 37 11 PM" src="https://user-images.githubusercontent.com/1172461/142735966-e0dff3d1-8535-4b65-85b7-d3972ff6dabe.png">

**Comment by Binetri** [comment]
In Outlook and Office 365 at **"No styles on td"** the border is drawn at the distance specified in the `padding: 13px 17px;` of `<a>`, and the background fill is only based on the size of the text? Am I getting it right? Inconceivable...

**Comment by TedGoas** [comment]
Yes, unfortunately you're reading that right :/

**Comment by Binetri** [comment]
Thanks a lot, Ted! According to your observations, the online version of the Outlook has the same problems as the desktop version?

**Comment by TedGoas** [comment]
I don't believe Outlook.com has the same problems. The Outlook mobile apps should be fine too. It's basically the email clients that use MS Word on Windows to render email that have this problem.

**Comment by Binetri** [comment]
Does Windows Mail have the same problems as the desktop Outlook? Please advise how legally test templates without buying a desktop Outlook.

**Comment by TedGoas** [comment]
I've been testing using [Email on Acid](https://www.emailonacid.com) to preview these in email clients. There's also [Litmus](https://www.litmus.com). They're not free, but you can trial them for free to test this on your end.

**Comment by Binetri** [comment]
Thanks, Ted. The issue can be closed.
