### ISSUE TITLE
Missing word in documentation?

### ISSUE THREAD

**Issue by hynes-dialpad** [TedGoas/Cerberus#279]
<img width="697" alt="image" src="https://user-images.githubusercontent.com/44445385/153619954-ff339c4a-d92f-42ed-911d-b23575b538c2.png">

Found under the Templates > CSS Inliners sections, it appears the second sentence is missing a word: "The CSS in the [email? template?] is only…"

**Comment by TedGoas** [comment]
Shoot, good catch, will fix!
