### ISSUE TITLE
Template issue when forwarding a sent email from Outlook to Gmail on iphone

### ISSUE THREAD

**Issue by miamimabel** [TedGoas/Cerberus#287]
**Describe the bug**
Hi Ted! I'm trying to troubleshoot an issue with the template when **forwarding a sent email** from **Outlook to Gmail** -- for iPhone users, the forwarded content looks like this:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/44374217/156226797-ba36951e-24b9-445e-b968-634d27652f90.png)

The template looks fine when forwarding from Outlook to Gmail on an Android phone.

**To Reproduce**
1. Which template? **Using Hybrid template**
2. Which email clients and/or devices are affected? **Gmail (from an Outlook forwarded email) on iPhone.**

**Screenshots**

**Comment by TedGoas** [comment]
@miamimabel The screenshots above seem to be from a template that you edited, can you reproduce this issue using the original hybrid template in this repo?

Also controlling how emails are forwarded is notoriously difficult. There's a discussion over in #264 if you haven't already seen it.

**Comment by miamimabel** [comment]
Thanks so much for getting back to me so quickly!

I sent the original hybrid template to an Outlook email, which was forwarded to a Gmail account, and opened using the iPhone mail app.

The same issue appears – see attached. Again, it only seems to be happening for iPhones.

Thanks in advance for any suggestions.

Mabel

**Comment by TedGoas** [comment]
How are you sending the original email? Are you using an ESP? Can you post an image of what you see in iOS Mail?

And you mentioned this only happens on iPhones? Did you test other email clients that produced better results?

**Comment by miamimabel** [comment]
Yes, we use an ESP. Below is the screenshot of the issue on iPhones. I tested on an Android and did not have the same issue. 

Also, I tested a completely different template to rule out the template, and it did not "break" this way.

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/44374217/156262595-c2102d7c-5ba9-4ab5-8d20-6dea86f496f1.png)

**Comment by TedGoas** [comment]
@miamimabel I'll be honest with you, getting email to display correctly in Outlook is hard enough. Figuring out what it's doing when forwarding might be beyond my skill set here. That said, I have a few more questions:

1. You mentioned you tried to troubleshoot this, can you describe what you've tried so far and the results you've seen?
2. Can you reproduce this error using [cerberus-fluid.html](https://github.com/TedGoas/Cerberus/blob/main/cerberus-fluid.html)? There's some tricky stuff going on in the hybrid template and I wonder if a simpler template might fare better after being forwarded.

**Comment by miamimabel** [comment]
Hi Ted. 

I tried with the Fluid template and it also shows the same issue (see screenshot below.) I also tried several other random emails that I’ve received – and it seems to be a common issue, though I did find one that didn't have the issue at all (see below).

From the (limited) testing I’ve done, it seems to only be an issue when forwarding from Outlook on (desktop or webmail only) and opening in Apple mail. However, if forwarding from Outlook Mail App and opening in Apple mail – the issue is not present.

I understand if there’s nothing more to do. (Oh Outlook, how I loathe you!) 

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/44374217/156809234-54f8f8ac-e5cd-4d0e-9ebd-7699fdc68351.png)

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/44374217/156810172-3629eaae-3fac-4ca0-a52e-c02de30194da.png)

**Comment by TedGoas** [comment]
@miamimabel Hmm honestly I don't think I'll be able to help much here. I don't have a desktop version of Outlook to help troubleshot this, on top of the fact that forwarded emails are generally hard to render properly. If you have any breakthroughs in your own testing, I'd love to hear about them!
