### ISSUE TITLE
Responsive Template: 1px line in Full Bleed Background Section in Outlook 2019

### ISSUE THREAD

**Issue by schindlerchristian** [TedGoas/Cerberus#290]
Hi Ted,

thank you for your great work - Cerberus helped me a lot to get started with responsive E-Mail Templating! 

Maybe you (or somebody else here) could help me to fix one little issue: As already mentioned in the title Outlook 2019 shows a 1px line in the color of the body background in the Full Bleed Background Section.

<img width="1132" alt="Screenshot 2022-06-07 at 12 33 26" src="https://user-images.githubusercontent.com/222685/172373308-a8aa5ab4-a61c-4b73-9882-56a364f0ba66.png">

I already tried to set the background of the div to the same color as the Full Bleed Background Section, to set "border-bottom: none" and "border-bottom: 0px" and some other border-settings - without any success.

Kind regards, Christian

**Comment by schindlerchristian** [comment]
Hello again...

Now I found a fix for the problem:

Strangely enough (or maybe just normal for Outlook) it works for me when I use "border-bottom: 0px solid #xyz;" (xyz= color of the background). If I just set it to "border: 0px;" or if I use a different color than the background-color, it does not work for me. The div bottom border has to be the same color as the color of the Full Bleed Background.

Here the complete code for the Full Bleed Background Section as it works fine for me:

`
	    <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="background-color: #709f2b;">
	        <tr>
	            <td>
	                <div align="center" style="border-bottom: 0px solid #709f2b; background-color: #709f2b; max-width: 600px; margin: auto;" class="email-container">
	                    
	                    <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%">
	                        <tr>
	                            <td style="padding: 20px; text-align: left; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #ffffff;">
	                                <p style="margin: 0;">Maecenas sed ante pellentesque, posuere leo id, eleifend dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent laoreet malesuada cursus. Maecenas scelerisque congue eros eu posuere. Praesent in felis ut velit pretium lobortis rhoncus ut&nbsp;erat.</p>
	                            </td>
	                        </tr>
	                    </table>
	                    
	                </div>
	            </td>
	        </tr>
	    </table>
	    `

Kind regards, Christian

**Comment by TedGoas** [comment]
@mediakreativ I'm glad you were able to work around this. I looked into this but cannot reproduce this behavior on my end. This is what I see in Email on Acid for Outlook 2019 on Win 10:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/1172461/172949380-89242937-4940-48a1-a94f-435f14d090e1.png">

---

Other versions of Windows Outlook show the same thing. Is your screenshot from an actual copy of Windows Outlook? Or are you also using a tool like Email on Acid or Litmus?
