### ISSUE TITLE
Darkmode / Lightmode confused by multiple appearance preferences in outlook.com

### ISSUE THREAD

**Issue by rosethroop** [TedGoas/Cerberus#298]
Thank you for your templates. I am working off of the cerberus fluid  template. I am noticing some odd behaviors in outlook.com email on a mac in edge and chrome browsers which cause issues when the browsers appearance preference and outlook.com's appearance don't agree. Not sure if this qualifies as bug (not yours anyway) or maybe this is this just an edge case worry since the user can fix it by making their preferences agree?

<img width="2044" alt="Screen Shot 2023-03-29 at 1 14 33 PM" src="https://user-images.githubusercontent.com/111949864/228622958-c8dccd1f-eb2d-400a-9b69-f5074496b100.png">
<img width="2043" alt="Screen Shot 2023-03-29 at 1 13 59 PM" src="https://user-images.githubusercontent.com/111949864/228622959-2d72d9e4-a706-449e-ba39-df887ef5d862.png">

**Comment by TedGoas** [comment]
Yea I've been having issues with this as well. Some dark mode styles being applied and then [Outlook.com](http://outlook.com/) doing some random stuff. Cerberus's dark mode relies on the OS setting to set the theme and it's quite possible [Outlook.com](http://outlook.com/) is doing it's own theming on top of that. Makes me wonder if we can hide the dark-mode styles from [Outlook.com](http://outlook.com/)? I don't see that in https://www.howtotarget.email/ but maybe there's a way.

**Comment by tedgoas-dialpad** [comment]
@rosethroop Hmm, I haven't been able to replicate this bug 😖 but you're not the only one who's reported seeing something like this.

Can you give me a little more info about the screenshots above?
- Is this on MacOS, Windows, or something else?
- Is this a free Outlook.com account or OWA for a business account?

---

I'm using a free, personal Outlook.com account on a Mac using Chrome, and even when I mis-match my OS and Outlook themes, the email still renders correctly:

<img width="1523" alt="Screenshot 2023-04-07 at 2 37 53 PM" src="https://user-images.githubusercontent.com/65190890/230661987-f1e688df-8a6e-4d58-8ed9-c3a164ace23e.png">

<img width="1522" alt="Screenshot 2023-04-07 at 2 38 37 PM" src="https://user-images.githubusercontent.com/65190890/230662001-35604fda-17e3-44f5-9b6c-7fdbafe7c728.png">

**Comment by tedgoas-dialpad** [comment]
Looks like there are [a few ways to target Outlook.com](https://www.howtotarget.email/) but I can't test or verify if one of these work since I can't see the issue in the first place.

**Comment by rosethroop** [comment]
Thank you for your pursuit of the question. I am on MacOS (10.14.6) using
browser with free outlook.com (Microsoft Edge Version 111.0.1661.62
(Official build) (x86_64) I can recreate a similar scenario in Google
Chrome (Version 112.0.5615.49 (Official Build) (x86_64)). Chrome adopts the
Mac OS Appearance preference so when outlook and the system disagree, the
results are half-baked dark mode.

Thank you so much for your efforts!
Rose


Rose Throop ’95 (she, her, hers)

Director of Integrated Marketing and Content

(315) 312-3657  |  ***@***.***

**Comment by TedGoas** [comment]
Are you still seeing this issue/ I was tracking a similar issue at my day job, and half-way through helping a client, they reported the issue fixed without me doing anything. We guessed Microsoft made a change on their end. I don't suppose we could be that lucky?

**Comment by rosethroop** [comment]
It does seem to have been resolved by Microsoft! TY!
R.

**Comment by TedGoas** [comment]
🎉🎉🎉
