### ISSUE TITLE
Looks like the website is broken (`hljs is not defined`)

### ISSUE THREAD

**Issue by daniel-keogh** [TedGoas/Cerberus#299]
**Describe the bug**

👋 Hey, looks like the website doesn't load as expected anymore

```console
(index):186 Uncaught ReferenceError: hljs is not defined
    at (index):186:11
```

**Screenshots**

<img width="2557" alt="Screenshot 2023-09-06 at 19 20 40" src="https://github.com/TedGoas/Cerberus/assets/37158241/39f927dd-3c27-44cf-bb9b-618c461dc0ae">

**Comment by TedGoas** [comment]
Welp, that's not good! Thanks for pointing this out. Look like there's an issue with how the site was configured and deployed, I'll try to fix asap!

**Comment by TedGoas** [comment]
@daniel-keogh Got the site redeployed and displaying properly. Thanks again for creating an issue for this!
