### ISSUE TITLE
Website/Parcel links point at templates from master, not main

### ISSUE THREAD

**Issue by DragoonAethis** [TedGoas/Cerberus#300]
All changes are currently being done on the `main` branch, but the [templates site](https://www.cerberusemail.com/templates) still links to their versions from `master` which are now outdated.

**Comment by TedGoas** [comment]
Hi, just wanted to let you know that I see this and understand the issue, I just have to work out a technical issue so I can publish changes to the site again. Thanks for pointing this out and sorry this simple change is taking so long.

**Comment by DragoonAethis** [comment]
No worries, thanks for your work!

**Comment by TedGoas** [comment]
Should be fixed now, thanks again for catching this!
